// blog_vite/src/components/Navbar.jsx
import { NavLink } from 'react-router-dom';

const desktop = ({ isActive }) =>
  `nav-link flex items-center justify-center p-2 rounded-full transition-all ease-in-out duration-200 ${isActive ? 'nav-active' : ''}`;

const mobile = ({ isActive }) =>
  `nav-link flex flex-col items-center justify-center p-3 rounded-full transition-all ease-in-out duration-200 ${isActive ? 'nav-active' : ''}`;

export default function Navbar() {
  return (
    <>
      {/* side nav (desktop) */}
      <div className="h-dvh w-17.5 px-2 py-10 bg-[#EDF5FA] shadow-nav flex-col items-center sticky top-0 left-0 hidden lg:flex z-50">
        <div className="flex items-center justify-center">
          <img src="/imgs/profile.png" alt="Profile Picture" className="h-12 w-12 rounded-full" />
        </div>
        <div className="flex flex-col gap-10 my-16">
          <NavLink to="/" end className={desktop}>
            <img src="/imgs/icon/home.svg" alt="Home" className="h-7 w-7" />
          </NavLink>
          <NavLink to="/posts" className={desktop}>
            <img src="/imgs/icon/blog.svg" alt="Blog" className="h-7 w-7" />
          </NavLink>
          <NavLink to="/notes" className={desktop}>
            <img src="/imgs/icon/note.svg" alt="Note" className="h-7 w-7" />
          </NavLink>
        </div>
        <a href="#/" className="nav-link flex items-center justify-center p-2 rounded-full mt-auto transition-all ease-in-out duration-200">
          <img src="/imgs/icon/settings.svg" alt="Settings" className="h-7 w-7" />
        </a>
      </div>

      {/* mobile nav */}
      <div className="lg:hidden fixed bottom-0 left-0 right-0 z-50 bg-[#EDF5FA] shadow-nav pb-[env(safe-area-inset-bottom)]">
        <div className="flex justify-around items-center py-3 px-4">
          <NavLink to="/" end className={mobile}>
            <img src="/imgs/icon/home.svg" alt="Home" className="h-6 w-6" />
          </NavLink>
          <NavLink to="/posts" className={mobile}>
            <img src="/imgs/icon/blog.svg" alt="Blog" className="h-6 w-6" />
          </NavLink>
          <NavLink to="/notes" className={mobile}>
            <img src="/imgs/icon/note.svg" alt="Note" className="h-6 w-6" />
          </NavLink>
          <a href="#/" className="nav-link flex flex-col items-center justify-center p-3 rounded-full transition-all ease-in-out duration-200">
            <img src="/imgs/icon/settings.svg" alt="Settings" className="h-6 w-6" />
          </a>
        </div>
      </div>
    </>
  );
}

// blog_svelte/src/lib/components/Navbar.svelte
<script lang="ts">
	import { homeClickCallback } from '$lib/stores.js';
	import { page } from '$app/state';

	function handleHomeClick(e: MouseEvent) {
		const cb = $homeClickCallback;
		if (cb) {
			e.preventDefault();
			cb();
		}
	}

	let isHome = $derived(page.url.pathname === '/');
	let isList = $derived(page.url.pathname === '/post-list');
	let isNote = $derived(page.url.pathname === '/note');
</script>

<!-- Desktop Side Nav -->
<div
	class="h-dvh w-17.5 px-2 py-10 bg-[#EDF5FA] shadow-nav flex-col items-center sticky top-0 left-0 hidden lg:flex shrink-0"
>
	<!-- Profile -->
	<div class="flex items-center justify-center">
		<img src="/imgs/profile.png" alt="Tony2100" class="h-12 w-12 rounded-full" />
	</div>

	<!-- Nav Items -->
	<div class="flex flex-col gap-10 my-16">
		<a
			href="/"
			onclick={handleHomeClick}
			class="flex items-center justify-center p-2 rounded-full transition-all duration-200 ease-in-out
			{isHome ? 'bg-[#DBECF8] shadow-inner' : 'hover:bg-[#e8f6ff] hover:shadow-inner'}"
		>
			<img src="/imgs/icon/home.svg" alt="首頁" class="h-7 w-7" />
		</a>
		<a
			href="/post-list"
			class="flex items-center justify-center p-2 rounded-full transition-all duration-200 ease-in-out
			{isList ? 'bg-[#DBECF8] shadow-inner' : 'hover:bg-[#e8f6ff] hover:shadow-inner'}"
		>
			<img src="/imgs/icon/blog.svg" alt="文章列表" class="h-7 w-7" />
		</a>
		<a
			href="/note"
			class="flex items-center justify-center p-2 rounded-full transition-all duration-200 ease-in-out
			{isNote ? 'bg-[#DBECF8] shadow-inner' : 'hover:bg-[#e8f6ff] hover:shadow-inner'}"
		>
			<img src="/imgs/icon/note.svg" alt="隨手記" class="h-7 w-7" />
		</a>
	</div>

	<!-- Settings -->
	<button
		class="flex items-center justify-center p-2 rounded-full mt-auto hover:bg-[#e8f6ff] hover:shadow-inner ease-in-out duration-200"
		aria-label="設定"
	>
		<img src="/imgs/icon/settings.svg" alt="設定" class="h-7 w-7" />
	</button>
</div>

<!-- Mobile Bottom Nav -->
<div
	class="lg:hidden fixed bottom-0 left-0 right-0 z-50 bg-[#EDF5FA] shadow-nav pb-[env(safe-area-inset-bottom)]"
>
	<div class="flex justify-around items-center py-3 px-4">
		<a
			href="/"
			onclick={handleHomeClick}
			class="flex flex-col items-center justify-center p-3 rounded-full transition-all duration-200 ease-in-out
			{isHome ? 'bg-[#DBECF8] shadow-inner' : ''}"
		>
			<img src="/imgs/icon/home.svg" alt="首頁" class="h-6 w-6" />
		</a>
		<a
			href="/post-list"
			class="flex flex-col items-center justify-center p-3 rounded-full transition-all duration-200 ease-in-out
			{isList ? 'bg-[#DBECF8] shadow-inner' : ''}"
		>
			<img src="/imgs/icon/blog.svg" alt="文章列表" class="h-6 w-6" />
		</a>
		<a
			href="/note"
			class="flex flex-col items-center justify-center p-3 rounded-full transition-all duration-200 ease-in-out
			{isNote ? 'bg-[#DBECF8] shadow-inner' : ''}"
		>
			<img src="/imgs/icon/note.svg" alt="隨手記" class="h-6 w-6" />
		</a>
		<button
			class="flex flex-col items-center justify-center p-3 rounded-full ease-in-out duration-200"
			aria-label="設定"
		>
			<img src="/imgs/icon/settings.svg" alt="設定" class="h-6 w-6" />
		</button>
	</div>
</div>
